/**
 * Arturia MicroFreak factory presets (FW 1.1 + FW 2.0).
 *
 * 160 presets from FW 1.1 (128 performance + 32 templates)
 * + 64 presets from FW 2.0 (introduced Noise oscillator + percussion sounds)
 * = 224 total
 *
 * Categories mapped to SoundCategory type from types.ts.
 * Engine is "synth" for all (MicroFreak is single-engine).
 * bankMSB: 0 for presets 1-128, 1 for 129+
 * programNumber: (id - 1) % 128
 */

import type { SoundPreset, SoundCategory } from "./types";

function mf(id: number, name: string, category: SoundCategory): SoundPreset {
  return {
    id,
    name,
    category,
    engine: "awm2", // using awm2 as generic synth engine for compatibility
    bankMSB: id <= 128 ? 0 : 1,
    bankLSB: 0,
    programNumber: (id - 1) % 128,
  };
}

export const MICROFREAK_PRESETS: SoundPreset[] = [
  // ─── FW 1.1 Performance Presets (1-128) ───────────────────────
  mf(1, "Disrespectful", "SFX"),
  mf(2, "Punisher", "Bass"),
  mf(3, "Trance", "Pad"),
  mf(4, "Ether", "Synth Lead"),
  mf(5, "MotivSeq", "Rhythmic"),
  mf(6, "Aft-WavPad", "Pad"),
  mf(7, "Brd But Arp", "Rhythmic"),
  mf(8, "IDm5", "Rhythmic"),
  mf(9, "261e", "Bass"),
  mf(10, "Invitation", "Pad"),
  mf(11, "Club V", "Rhythmic"),
  mf(12, "Ringcussion", "SFX"),
  mf(13, "Pikdown", "SFX"),
  mf(14, "Michtack", "Rhythmic"),
  mf(15, "PolyBells", "Synth Lead"),
  mf(16, "Number Station", "SFX"),
  mf(17, "Tubular", "Bell"),
  mf(18, "Chip", "Rhythmic"),
  mf(19, "BrightBinary", "Synth Lead"),
  mf(20, "Arp-fi", "Keyboard"),
  mf(21, "Short Strings", "Strings"),
  mf(22, "Raverz", "Rhythmic"),
  mf(23, "AliGoop", "Keyboard"),
  mf(24, "Stan2", "Keyboard"),
  mf(25, "808 St8 M8", "Rhythmic"),
  mf(26, "L9n1", "Rhythmic"),
  mf(27, "Voidom", "SFX"),
  mf(28, "Daft", "Rhythmic"),
  mf(29, "Bontempis", "Keyboard"),
  mf(30, "HarmonicTuneUp", "SFX"),
  mf(31, "Ixos", "Synth Lead"),
  mf(32, "Chord Bass", "Bass"),
  mf(33, "BouncKeyPara", "Rhythmic"),
  mf(34, "Corrosion", "Bass"),
  mf(35, "FM Seq", "Rhythmic"),
  mf(36, "Rollie Lov", "Rhythmic"),
  mf(37, "Chunk", "Bass"),
  mf(38, "Classist", "Brass"),
  mf(39, "Nostromo", "Rhythmic"),
  mf(40, "Jo5td", "Rhythmic"),
  mf(41, "Madtraker", "SFX"),
  mf(42, "Hoss", "Pad"),
  mf(43, "SineLow", "Rhythmic"),
  mf(44, "FM-it", "SFX"),
  mf(45, "Lottreux", "Pad"),
  mf(46, "XnastX", "Bass"),
  mf(47, "White Calx", "Pad"),
  mf(48, "VintageEdge", "Rhythmic"),
  mf(49, "Sci Organ", "Organ"),
  mf(50, "Death", "SFX"),
  mf(51, "Solitude", "Keyboard"),
  mf(52, "NervousKeys", "Keyboard"),
  mf(53, "Crystal", "SFX"),
  mf(54, "Rebel", "Synth Lead"),
  mf(55, "Analordic", "Pad"),
  mf(56, "PowerStab", "Synth Lead"),
  mf(57, "Hollows", "Rhythmic"),
  mf(58, "Junk.J", "SFX"),
  mf(59, "Suby Rainbow", "SFX"),
  mf(60, "Unstable Solo", "Synth Lead"),
  mf(61, "AftrBlush", "Rhythmic"),
  mf(62, "Recollection", "Keyboard"),
  mf(63, "Mood Strings", "Strings"),
  mf(64, "Acid Grain", "Rhythmic"),
  mf(65, "Kendrok", "Keyboard"),
  mf(66, "Mood", "Keyboard"),
  mf(67, "Cafe Chords", "Keyboard"),
  mf(68, "Grain Pad", "Pad"),
  mf(69, "Vanarx", "Bass"),
  mf(70, "Angels", "Pad"),
  mf(71, "Canadian Bass", "Bass"),
  mf(72, "3opR", "Rhythmic"),
  mf(73, "Cliched Things", "Bass"),
  mf(74, "Sweep SQ", "Rhythmic"),
  mf(75, "Buzzsaw", "SFX"),
  mf(76, "S.H Ld", "Synth Lead"),
  mf(77, "Sneaker", "Bass"),
  mf(78, "Saying Goodbye", "Pad"),
  mf(79, "AutoCHILL", "Pad"),
  mf(80, "Eonz", "Synth Lead"),
  mf(81, "A Juno Vibe", "Pad"),
  mf(82, "ArpZap", "Synth Lead"),
  mf(83, "Tradition", "Rhythmic"),
  mf(84, "Gaming", "Rhythmic"),
  mf(85, "Over Me", "Rhythmic"),
  mf(86, "Leeds Strings", "Strings"),
  mf(87, "Press So", "Keyboard"),
  mf(88, "Invaders", "Rhythmic"),
  mf(89, "On Harm", "Synth Lead"),
  mf(90, "Arp 2019", "Rhythmic"),
  mf(91, "Whimsy", "Pad"),
  mf(92, "ATSpookBass", "Bass"),
  mf(93, "D-Funk", "Rhythmic"),
  mf(94, "Kleo", "Pad"),
  mf(95, "Guisky", "Rhythmic"),
  mf(96, "Cathill", "Rhythmic"),
  mf(97, "Smooth Pd", "Keyboard"),
  mf(98, "Language", "SFX"),
  mf(99, "Blind", "Keyboard"),
  mf(100, "Gloudal", "Keyboard"),
  mf(101, "Boers", "Bass"),
  mf(102, "Trapeurz", "Pad"),
  mf(103, "SH Stutter", "Pad"),
  mf(104, "Lo-FiOrgan", "Organ"),
  mf(105, "Loose Tab", "Bell"),
  mf(106, "Tout Doux", "Pad"),
  mf(107, "Tinnendo", "Keyboard"),
  mf(108, "GroovE", "Rhythmic"),
  mf(109, "GlitchMachine", "SFX"),
  mf(110, "Etna 01", "Rhythmic"),
  mf(111, "Braine Storm", "Keyboard"),
  mf(112, "Padel", "Pad"),
  mf(113, "Wait...", "Rhythmic"),
  mf(114, "BotsDying", "SFX"),
  mf(115, "Vale", "Rhythmic"),
  mf(116, "SlowBurn", "Pad"),
  mf(117, "Steppad", "Pad"),
  mf(118, "Clave String", "Strings"),
  mf(119, "Darkstream", "Strings"),
  mf(120, "Arame", "Keyboard"),
  mf(121, "ATZap", "SFX"),
  mf(122, "Organism", "Organ"),
  mf(123, "VeloSparklz", "Bass"),
  mf(124, "Nost", "Pad"),
  mf(125, "TechniChords", "SFX"),
  mf(126, "F-Back", "Bass"),
  mf(127, "AcidFrog", "Bass"),
  mf(128, "Anlg", "Bass"),

  // ─── FW 1.1 Template Presets (129-160) ────────────────────────
  mf(129, "Square Poly", "Keyboard"),
  mf(130, "Keys 1", "Keyboard"),
  mf(131, "Keys 2", "Keyboard"),
  mf(132, "7th Keys", "Keyboard"),
  mf(133, "Toy Piano", "Piano"),
  mf(134, "Vibra", "Mallet"),
  mf(135, "JP Strings", "Strings"),
  mf(136, "Xylophone", "Mallet"),
  mf(137, "Strings 1", "Strings"),
  mf(138, "Strings 2", "Strings"),
  mf(139, "KarpluStrings", "Strings"),
  mf(140, "Karpad", "Pad"),
  mf(141, "Brass 1", "Brass"),
  mf(142, "Brass 2", "Brass"),
  mf(143, "Soft Brass", "Brass"),
  mf(144, "Organ 1", "Organ"),
  mf(145, "Organ 2", "Organ"),
  mf(146, "Glass Organ", "Organ"),
  mf(147, "Night Organ", "Organ"),
  mf(148, "Chorgan", "Organ"),
  mf(149, "Fusion Lead", "Synth Lead"),
  mf(150, "Lucky Lead", "Synth Lead"),
  mf(151, "FM Bass", "Bass"),
  mf(152, "Saw Bass", "Bass"),
  mf(153, "Square Bass", "Bass"),
  mf(154, "Acid Bass 2", "Bass"),
  mf(155, "Acid Bass 1", "Bass"),
  mf(156, "Simple Sub", "Bass"),
  mf(157, "Exotic Perc", "Bell"),
  mf(158, "Bells 1", "Bell"),
  mf(159, "Bells 2", "Bell"),
  mf(160, "SubOscTemplate", "Bass"),

  // ─── FW 2.0 Presets (161-224) ─────────────────────────────────
  mf(161, "D3 Chords", "Rhythmic"),
  mf(162, "Fate In Freaks", "Bass"),
  mf(163, "Notobeat", "Rhythmic"),
  mf(164, "Analog Chaser", "Rhythmic"),
  mf(165, "Minor Pad", "Pad"),
  mf(166, "Fight", "Synth Lead"),
  mf(167, "NoiseBusters", "Keyboard"),
  mf(168, "Jobs 4 Rhythm", "Bell"),
  mf(169, "Fat Moves", "Rhythmic"),
  mf(170, "Simon Says", "Rhythmic"),
  mf(171, "TaBass", "Bass"),
  mf(172, "Luna5", "Rhythmic"),
  mf(173, "Amigras", "Rhythmic"),
  mf(174, "Snitch 5", "Rhythmic"),
  mf(175, "Filicophyta", "Pad"),
  mf(176, "KickBass", "Bass"),
  mf(177, "HH Seq One", "Rhythmic"),
  mf(178, "Evo Arp", "Synth Lead"),
  mf(179, "Colik", "Keyboard"),
  mf(180, "Hold Riser", "SFX"),
  mf(181, "Malfunction", "Rhythmic"),
  mf(182, "Qbit Brass", "Brass"),
  mf(183, "No Sleep", "Rhythmic"),
  mf(184, "Chip Thunder", "SFX"),
  mf(185, "Solide", "Synth Lead"),
  mf(186, "Metallic Talk", "SFX"),
  mf(187, "Long FM Bass", "Bass"),
  mf(188, "Hats Maker", "SFX"),
  mf(189, "Digital Sea", "SFX"),
  mf(190, "Kick A", "SFX"),
  mf(191, "Kick B", "SFX"),
  mf(192, "Hihat A", "SFX"),
  mf(193, "Hihat B", "SFX"),
  mf(194, "Snare Seq 1", "Rhythmic"),
  mf(195, "Drum Grit Seq", "Rhythmic"),
  mf(196, "Mad Drums", "SFX"),
  mf(197, "Colt", "Keyboard"),
  mf(198, "Stab One", "Synth Lead"),
  mf(199, "The Unstable", "Pad"),
  mf(200, "B3", "SFX"),
  mf(201, "Pig", "Keyboard"),
  mf(202, "Old Tapes", "Pad"),
  mf(203, "Paralex", "Rhythmic"),
  mf(204, "Prosper", "Rhythmic"),
  mf(205, "Ice Cold", "Keyboard"),
  mf(206, "Grimy Beat", "Rhythmic"),
  mf(207, "Snow Man", "Synth Lead"),
  mf(208, "Incoming Ship", "SFX"),
  mf(209, "Crackle Sleep", "Pad"),
  mf(210, "Roid", "Rhythmic"),
  mf(211, "Sausage Bass", "Bass"),
  mf(212, "Space Alert", "SFX"),
  mf(213, "Kick N Hard", "SFX"),
  mf(214, "Rnd Rytm Arp", "Synth Lead"),
  mf(215, "Chordrone It", "Pad"),
  mf(216, "Arpic", "Rhythmic"),
  mf(217, "Pats", "SFX"),
  mf(218, "Shaka", "SFX"),
  mf(219, "Prof", "Keyboard"),
  mf(220, "Snare Four", "SFX"),
  mf(221, "AfterBurner", "SFX"),
  mf(222, "Auster", "Keyboard"),
  mf(223, "Wuuut", "SFX"),
  mf(224, "Sayan 2", "SFX"),
];
