#!/usr/bin/env python3
"""
SeqTrak Composer — CLI tool for creating and converting MIDI files
compatible with the Yamaha Seqtrak groovebox.

Supports:
  - Composing patterns from scratch (step sequencer + scale-aware note entry)
  - Importing existing MIDI files and remapping to Seqtrak's channel layout
  - Exporting multi-channel MIDI files mapped to Seqtrak's 11 tracks
  - Project save/load (JSON format)

Yamaha Seqtrak MIDI Channel Mapping:
  Ch 1: Kick       (Drum)      Ch 5: Hat 2     (Drum)      Ch 9:  Synth 2  (AWM2)
  Ch 2: Snare      (Drum)      Ch 6: Perc 1    (Drum)      Ch 10: DX       (FM)
  Ch 3: Clap       (Drum)      Ch 7: Perc 2    (Drum)      Ch 11: Sampler
  Ch 4: Hat 1      (Drum)      Ch 8: Synth 1   (AWM2)

Author: Generated by Perplexity Computer for Minh Cao
"""

import json
import sys
import os
import copy
import argparse
from dataclasses import dataclass, field, asdict
from typing import Optional
from pathlib import Path

try:
    from mido import MidiFile, MidiTrack, Message, MetaMessage, bpm2tempo, tempo2bpm
except ImportError:
    print("Error: 'mido' package is required. Install with: pip install mido")
    sys.exit(1)

try:
    from rich.console import Console
    from rich.table import Table
    from rich.panel import Panel
    from rich.prompt import Prompt, IntPrompt, Confirm
    from rich.text import Text
    from rich.layout import Layout
    from rich.columns import Columns
    from rich import box
except ImportError:
    print("Error: 'rich' package is required. Install with: pip install rich")
    sys.exit(1)

console = Console()

# ─── Seqtrak Hardware Constants ──────────────────────────────────────────────

SEQTRAK_TRACKS = {
    1:  {"name": "Kick",    "type": "drum",    "color": "red"},
    2:  {"name": "Snare",   "type": "drum",    "color": "yellow"},
    3:  {"name": "Clap",    "type": "drum",    "color": "magenta"},
    4:  {"name": "Hat 1",   "type": "drum",    "color": "cyan"},
    5:  {"name": "Hat 2",   "type": "drum",    "color": "blue"},
    6:  {"name": "Perc 1",  "type": "drum",    "color": "green"},
    7:  {"name": "Perc 2",  "type": "drum",    "color": "white"},
    8:  {"name": "Synth 1", "type": "synth",   "color": "bright_magenta"},
    9:  {"name": "Synth 2", "type": "synth",   "color": "bright_cyan"},
    10: {"name": "DX",      "type": "fm",      "color": "bright_yellow"},
    11: {"name": "Sampler", "type": "sampler",  "color": "bright_green"},
}

MAX_PATTERNS_PER_TRACK = 6
MAX_BARS = 8
STEPS_PER_BAR = 16
MAX_STEPS = MAX_BARS * STEPS_PER_BAR  # 128
MAX_SCENES = 16
BPM_MIN = 5
BPM_MAX = 300
DEFAULT_BPM = 120
TICKS_PER_BEAT = 480  # Standard MIDI resolution
TICKS_PER_STEP = TICKS_PER_BEAT // 4  # 16th note = 1 step

# Musical scales (semitone intervals from root)
SCALES = {
    "chromatic":       [0,1,2,3,4,5,6,7,8,9,10,11],
    "major":           [0,2,4,5,7,9,11],
    "natural_minor":   [0,2,3,5,7,8,10],
    "harmonic_minor":  [0,2,3,5,7,8,11],
    "melodic_minor":   [0,2,3,5,7,9,11],
    "dorian":          [0,2,3,5,7,9,10],
    "phrygian":        [0,1,3,5,7,8,10],
    "lydian":          [0,2,4,6,7,9,11],
    "mixolydian":      [0,2,4,5,7,9,10],
    "locrian":         [0,1,3,5,6,8,10],
    "pentatonic_major":[0,2,4,7,9],
    "pentatonic_minor":[0,3,5,7,10],
    "blues":           [0,3,5,6,7,10],
    "whole_tone":      [0,2,4,6,8,10],
    "diminished":      [0,2,3,5,6,8,9,11],
}

NOTE_NAMES = ["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"]

QUANTIZE_OPTIONS = {
    "1/32":  TICKS_PER_BEAT // 8,
    "1/16T": TICKS_PER_BEAT // 6,
    "1/16":  TICKS_PER_BEAT // 4,
    "1/8T":  TICKS_PER_BEAT // 3,
    "1/8":   TICKS_PER_BEAT // 2,
    "off":   1,
}


# ─── Data Models ─────────────────────────────────────────────────────────────

def note_name_to_midi(name: str) -> int:
    """Convert note name like 'C4', 'F#3', 'Bb5' to MIDI note number."""
    name = name.strip()
    if not name:
        raise ValueError("Empty note name")
    
    # Handle flats
    name = name.replace("Bb", "A#").replace("Db", "C#").replace("Eb", "D#")
    name = name.replace("Gb", "F#").replace("Ab", "G#")
    name = name.replace("bb", "A#").replace("db", "C#").replace("eb", "D#")
    name = name.replace("gb", "F#").replace("ab", "G#")
    
    # Parse note and octave
    if len(name) >= 2 and name[1] == '#':
        note_part = name[:2]
        octave_part = name[2:]
    else:
        note_part = name[0].upper()
        octave_part = name[1:]
    
    note_part = note_part.upper()
    if note_part not in NOTE_NAMES:
        raise ValueError(f"Unknown note: {note_part}")
    
    try:
        octave = int(octave_part)
    except ValueError:
        raise ValueError(f"Invalid octave in '{name}'")
    
    return (octave + 1) * 12 + NOTE_NAMES.index(note_part)


def midi_to_note_name(midi_note: int) -> str:
    """Convert MIDI note number to note name like 'C4'."""
    octave = (midi_note // 12) - 1
    note = NOTE_NAMES[midi_note % 12]
    return f"{note}{octave}"


def get_scale_notes(root: str, scale_name: str, octave_start: int = 2, octave_end: int = 6) -> list:
    """Generate all MIDI notes in a scale within the given octave range."""
    if scale_name not in SCALES:
        raise ValueError(f"Unknown scale: {scale_name}")
    
    root_idx = NOTE_NAMES.index(root.upper().replace("b", "#"))
    intervals = SCALES[scale_name]
    notes = []
    
    for octave in range(octave_start, octave_end + 1):
        for interval in intervals:
            midi_note = (octave + 1) * 12 + root_idx + interval
            if 0 <= midi_note <= 127:
                notes.append(midi_note)
    
    return sorted(set(notes))


@dataclass
class Note:
    """A single note event."""
    pitch: int          # MIDI note number (0-127)
    velocity: int = 100 # 1-127
    step: int = 0       # Step position (0-based)
    duration: int = 1   # Duration in steps (1 = 1/16th note)
    probability: int = 100  # 0-100, Seqtrak supports step probability
    
    def to_dict(self):
        return asdict(self)
    
    @classmethod
    def from_dict(cls, d):
        return cls(**d)


@dataclass
class Pattern:
    """A pattern for a single track (up to 8 bars / 128 steps)."""
    name: str = "Pattern 1"
    bars: int = 1          # 1-8 bars
    notes: list = field(default_factory=list)  # List of Note objects
    swing: int = 0         # -100 to +100
    
    @property
    def total_steps(self):
        return self.bars * STEPS_PER_BAR
    
    def add_note(self, pitch: int, step: int, velocity: int = 100, 
                 duration: int = 1, probability: int = 100):
        if step < 0 or step >= self.total_steps:
            raise ValueError(f"Step {step} out of range (0-{self.total_steps-1})")
        if pitch < 0 or pitch > 127:
            raise ValueError(f"Pitch {pitch} out of MIDI range (0-127)")
        velocity = max(1, min(127, velocity))
        
        note = Note(pitch=pitch, velocity=velocity, step=step, 
                    duration=duration, probability=probability)
        self.notes.append(note)
        return note
    
    def remove_note_at(self, step: int, pitch: Optional[int] = None):
        """Remove note(s) at a given step. If pitch is None, remove all notes at that step."""
        self.notes = [n for n in self.notes 
                      if not (n.step == step and (pitch is None or n.pitch == pitch))]
    
    def clear(self):
        self.notes.clear()
    
    def get_step_grid(self) -> dict:
        """Return a dict mapping step -> list of notes at that step."""
        grid = {}
        for note in self.notes:
            grid.setdefault(note.step, []).append(note)
        return grid
    
    def to_dict(self):
        return {
            "name": self.name,
            "bars": self.bars,
            "swing": self.swing,
            "notes": [n.to_dict() for n in self.notes],
        }
    
    @classmethod
    def from_dict(cls, d):
        p = cls(name=d["name"], bars=d["bars"], swing=d.get("swing", 0))
        p.notes = [Note.from_dict(n) for n in d["notes"]]
        return p


@dataclass
class Track:
    """A Seqtrak track with up to 6 patterns."""
    channel: int           # MIDI channel (1-11)
    patterns: list = field(default_factory=list)  # List of Pattern objects
    active_pattern: int = 0
    muted: bool = False
    volume: int = 100      # 0-127
    pan: int = 64          # 0-127 (64 = center)
    
    @property
    def info(self):
        return SEQTRAK_TRACKS[self.channel]
    
    @property
    def name(self):
        return self.info["name"]
    
    @property
    def track_type(self):
        return self.info["type"]
    
    @property
    def color(self):
        return self.info["color"]
    
    def ensure_patterns(self):
        """Ensure at least one pattern exists."""
        if not self.patterns:
            self.patterns.append(Pattern(name=f"Pattern 1"))
    
    def get_active_pattern(self) -> Pattern:
        self.ensure_patterns()
        return self.patterns[self.active_pattern]
    
    def add_pattern(self, name: Optional[str] = None) -> Pattern:
        if len(self.patterns) >= MAX_PATTERNS_PER_TRACK:
            raise ValueError(f"Maximum {MAX_PATTERNS_PER_TRACK} patterns per track")
        idx = len(self.patterns) + 1
        p = Pattern(name=name or f"Pattern {idx}")
        self.patterns.append(p)
        return p
    
    def to_dict(self):
        return {
            "channel": self.channel,
            "active_pattern": self.active_pattern,
            "muted": self.muted,
            "volume": self.volume,
            "pan": self.pan,
            "patterns": [p.to_dict() for p in self.patterns],
        }
    
    @classmethod
    def from_dict(cls, d):
        t = cls(channel=d["channel"], active_pattern=d["active_pattern"],
                muted=d["muted"], volume=d["volume"], pan=d["pan"])
        t.patterns = [Pattern.from_dict(p) for p in d["patterns"]]
        return t


@dataclass
class Scene:
    """A scene = a combination of active pattern indices per track + mutes."""
    name: str = "Scene 1"
    pattern_indices: dict = field(default_factory=dict)  # channel -> pattern_index
    mutes: dict = field(default_factory=dict)            # channel -> bool
    repeats: int = 1  # How many times to play this scene in song mode
    
    def to_dict(self):
        return asdict(self)
    
    @classmethod
    def from_dict(cls, d):
        return cls(**d)


@dataclass
class Project:
    """A Seqtrak project containing 11 tracks and up to 16 scenes."""
    name: str = "Untitled Project"
    bpm: int = DEFAULT_BPM
    tracks: dict = field(default_factory=dict)   # channel -> Track
    scenes: list = field(default_factory=list)    # List of Scene objects
    scale_root: str = "C"
    scale_name: str = "chromatic"
    quantize: str = "1/16"
    
    def __post_init__(self):
        # Initialize all 11 tracks if empty
        if not self.tracks:
            for ch in range(1, 12):
                t = Track(channel=ch)
                t.ensure_patterns()
                self.tracks[ch] = t
    
    def get_track(self, channel: int) -> Track:
        return self.tracks[channel]
    
    def to_dict(self):
        return {
            "name": self.name,
            "bpm": self.bpm,
            "scale_root": self.scale_root,
            "scale_name": self.scale_name,
            "quantize": self.quantize,
            "tracks": {str(k): v.to_dict() for k, v in self.tracks.items()},
            "scenes": [s.to_dict() for s in self.scenes],
        }
    
    @classmethod
    def from_dict(cls, d):
        p = cls.__new__(cls)
        p.name = d["name"]
        p.bpm = d["bpm"]
        p.scale_root = d.get("scale_root", "C")
        p.scale_name = d.get("scale_name", "chromatic")
        p.quantize = d.get("quantize", "1/16")
        p.tracks = {int(k): Track.from_dict(v) for k, v in d["tracks"].items()}
        p.scenes = [Scene.from_dict(s) for s in d.get("scenes", [])]
        return p
    
    def save(self, path: str):
        with open(path, 'w') as f:
            json.dump(self.to_dict(), f, indent=2)
        console.print(f"[green]Project saved to {path}[/green]")
    
    @classmethod
    def load(cls, path: str) -> 'Project':
        with open(path, 'r') as f:
            data = json.load(f)
        project = cls.from_dict(data)
        console.print(f"[green]Project loaded from {path}[/green]")
        return project


# ─── MIDI Export ─────────────────────────────────────────────────────────────

def export_midi(project: Project, path: str, export_all_patterns: bool = False):
    """
    Export project to a Standard MIDI File (Type 1) with Seqtrak channel mapping.
    
    Each track is exported on its corresponding MIDI channel (1-11).
    Drum tracks: each note trigger is exported as a single note-on at C3 (MIDI 60)
                 unless the pattern has specific pitch data.
    Synth tracks: notes are exported with their full pitch information.
    
    If export_all_patterns is True, patterns are concatenated sequentially.
    Otherwise, only the active pattern per track is exported.
    """
    mid = MidiFile(type=1, ticks_per_beat=TICKS_PER_BEAT)
    
    # Tempo track
    tempo_track = MidiTrack()
    mid.tracks.append(tempo_track)
    tempo_track.append(MetaMessage('set_tempo', tempo=bpm2tempo(project.bpm), time=0))
    tempo_track.append(MetaMessage('track_name', name=project.name, time=0))
    tempo_track.append(MetaMessage('time_signature', numerator=4, denominator=4, 
                                    clocks_per_click=24, notated_32nd_notes_per_beat=8, time=0))
    
    for ch in range(1, 12):
        track = project.get_track(ch)
        info = SEQTRAK_TRACKS[ch]
        midi_track = MidiTrack()
        mid.tracks.append(midi_track)
        midi_track.append(MetaMessage('track_name', name=info["name"], time=0))
        
        if track.muted:
            continue
        
        # Collect patterns to export
        if export_all_patterns:
            patterns_to_export = [p for p in track.patterns if p.notes]
        else:
            pattern = track.get_active_pattern()
            patterns_to_export = [pattern] if pattern.notes else []
        
        if not patterns_to_export:
            continue
        
        # Build absolute-time event list
        events = []
        step_offset = 0
        
        for pattern in patterns_to_export:
            for note in pattern.notes:
                abs_tick = (step_offset + note.step) * TICKS_PER_STEP
                duration_ticks = note.duration * TICKS_PER_STEP
                
                # MIDI channels are 0-indexed in mido
                midi_ch = ch - 1
                
                events.append((abs_tick, 'note_on', midi_ch, note.pitch, note.velocity))
                events.append((abs_tick + duration_ticks, 'note_off', midi_ch, note.pitch, 0))
            
            step_offset += pattern.total_steps
        
        # Sort by time, then note_off before note_on at same time
        events.sort(key=lambda e: (e[0], 0 if e[1] == 'note_off' else 1))
        
        # Convert to delta times
        last_tick = 0
        for evt in events:
            delta = evt[0] - last_tick
            last_tick = evt[0]
            midi_track.append(Message(evt[1], channel=evt[2], note=evt[3], 
                                       velocity=evt[4], time=delta))
    
    mid.save(path)
    console.print(f"[green]MIDI exported to {path}[/green]")
    console.print(f"  BPM: {project.bpm}, Tracks with data: "
                  f"{sum(1 for ch in range(1,12) if project.get_track(ch).get_active_pattern().notes)}")


# ─── MIDI Import ─────────────────────────────────────────────────────────────

def analyze_midi(path: str) -> dict:
    """Analyze a MIDI file and return channel/track info."""
    mid = MidiFile(path)
    info = {
        "filename": os.path.basename(path),
        "type": mid.type,
        "ticks_per_beat": mid.ticks_per_beat,
        "num_tracks": len(mid.tracks),
        "channels": {},
        "tempo": DEFAULT_BPM,
        "duration_seconds": mid.length,
    }
    
    for i, track in enumerate(mid.tracks):
        track_name = None
        for msg in track:
            if msg.type == 'track_name':
                track_name = msg.name
            elif msg.type == 'set_tempo':
                info["tempo"] = int(tempo2bpm(msg.tempo))
            elif msg.type in ('note_on', 'note_off') and hasattr(msg, 'channel'):
                ch = msg.channel + 1  # Convert to 1-indexed
                if ch not in info["channels"]:
                    info["channels"][ch] = {
                        "track_index": i,
                        "track_name": track_name,
                        "note_count": 0,
                        "note_range": [127, 0],
                        "notes": set(),
                    }
                if msg.type == 'note_on' and msg.velocity > 0:
                    info["channels"][ch]["note_count"] += 1
                    info["channels"][ch]["note_range"][0] = min(info["channels"][ch]["note_range"][0], msg.note)
                    info["channels"][ch]["note_range"][1] = max(info["channels"][ch]["note_range"][1], msg.note)
                    info["channels"][ch]["notes"].add(msg.note)
    
    # Convert sets to sorted lists for display
    for ch_info in info["channels"].values():
        ch_info["notes"] = sorted(ch_info["notes"])
    
    return info


def import_midi(path: str, project: Project, channel_map: Optional[dict] = None,
                quantize_to: str = "1/16", max_bars: int = 8):
    """
    Import a MIDI file into the project with optional channel remapping.
    
    channel_map: dict mapping source MIDI channel -> Seqtrak channel (1-11)
                 If None, channels are mapped directly (1->1, 2->2, etc.)
    """
    mid = MidiFile(path)
    tpb = mid.ticks_per_beat
    quant_ticks = QUANTIZE_OPTIONS.get(quantize_to, TICKS_PER_BEAT // 4)
    
    # Determine tempo
    for track in mid.tracks:
        for msg in track:
            if msg.type == 'set_tempo':
                project.bpm = int(tempo2bpm(msg.tempo))
                break
    
    # Collect all note events with absolute timing
    channel_notes = {}  # source_channel -> [(abs_tick, pitch, velocity, duration_ticks)]
    
    for track in mid.tracks:
        abs_tick = 0
        active_notes = {}  # (channel, pitch) -> (start_tick, velocity)
        
        for msg in track:
            abs_tick += msg.time
            
            if msg.type == 'note_on' and msg.velocity > 0:
                ch = msg.channel + 1
                active_notes[(ch, msg.note)] = (abs_tick, msg.velocity)
            
            elif msg.type == 'note_off' or (msg.type == 'note_on' and msg.velocity == 0):
                ch = msg.channel + 1
                key = (ch, msg.note)
                if key in active_notes:
                    start, vel = active_notes.pop(key)
                    dur = abs_tick - start
                    channel_notes.setdefault(ch, []).append((start, msg.note, vel, dur))
    
    # Calculate the scaling factor for tick conversion
    source_step_ticks = tpb / 4  # Source 16th note in ticks
    
    imported_count = 0
    max_step = max_bars * STEPS_PER_BAR
    
    for src_ch, notes in channel_notes.items():
        # Determine target channel
        if channel_map and src_ch in channel_map:
            tgt_ch = channel_map[src_ch]
        elif src_ch <= 11:
            tgt_ch = src_ch
        else:
            continue  # Skip channels > 11 that aren't mapped
        
        if tgt_ch < 1 or tgt_ch > 11:
            continue
        
        track = project.get_track(tgt_ch)
        # Use active pattern or add a new one
        pattern = track.get_active_pattern()
        
        for abs_tick, pitch, velocity, dur_ticks in notes:
            # Convert to step position
            step = round(abs_tick / source_step_ticks)
            
            # Quantize
            if quantize_to != "off":
                quant_steps = max(1, round(quant_ticks / source_step_ticks))
                step = round(step / quant_steps) * quant_steps
            
            if step >= max_step:
                continue
            
            # Calculate duration in steps
            dur_steps = max(1, round(dur_ticks / source_step_ticks))
            
            # Auto-expand pattern bars if needed
            needed_bars = (step // STEPS_PER_BAR) + 1
            if needed_bars > pattern.bars:
                pattern.bars = min(needed_bars, MAX_BARS)
            
            pattern.add_note(pitch=pitch, step=step, velocity=velocity, duration=dur_steps)
            imported_count += 1
    
    console.print(f"[green]Imported {imported_count} notes from {path}[/green]")
    return imported_count


# ─── Pattern Generation Helpers ──────────────────────────────────────────────

def generate_euclidean_rhythm(steps: int, pulses: int, rotation: int = 0) -> list:
    """Generate a Euclidean rhythm pattern. Returns list of step indices with hits."""
    if pulses > steps:
        pulses = steps
    if pulses == 0:
        return []
    
    pattern = []
    bucket = 0
    for i in range(steps):
        bucket += pulses
        if bucket >= steps:
            bucket -= steps
            pattern.append((i + rotation) % steps)
    
    return sorted(pattern)


def generate_drum_pattern(style: str, bars: int = 1) -> dict:
    """
    Generate a preset drum pattern. Returns dict: channel -> list of (step, velocity) tuples.
    
    Styles: basic_4x4, breakbeat, trap, house, techno, dnb, hiphop
    """
    total = bars * STEPS_PER_BAR
    patterns = {ch: [] for ch in range(1, 8)}
    
    def add(ch, steps, vel=100):
        for s in steps:
            for bar in range(bars):
                step = s + bar * STEPS_PER_BAR
                if step < total:
                    patterns[ch].append((step, vel))
    
    if style == "basic_4x4":
        add(1, [0, 4, 8, 12])                    # Kick on every beat
        add(2, [4, 12])                           # Snare on 2 & 4
        add(4, [0, 2, 4, 6, 8, 10, 12, 14])      # Hat on every 8th
        add(5, [2, 6, 10, 14], 70)                # Open hat offbeats
    
    elif style == "breakbeat":
        add(1, [0, 6, 10])                        # Syncopated kick
        add(2, [4, 12])                           # Snare on 2 & 4
        add(4, [0, 2, 4, 6, 8, 10, 12, 14])      # Closed hat
        add(3, [14], 80)                          # Clap pickup
    
    elif style == "trap":
        add(1, [0, 7, 8])                         # 808 kick
        add(2, [4, 12])                           # Snare
        add(4, [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15], 60)  # Fast hats
        add(5, [4, 12], 90)                       # Open hat on snare
        add(3, [4, 12], 85)                       # Clap with snare
    
    elif style == "house":
        add(1, [0, 4, 8, 12])                    # Four on the floor
        add(3, [4, 12])                           # Clap on 2 & 4
        add(4, [2, 6, 10, 14])                    # Offbeat hats
        add(6, [0, 8], 70)                        # Percussion
    
    elif style == "techno":
        add(1, [0, 4, 8, 12])                    # Four on the floor
        add(2, [4, 12])                           # Snare
        add(4, [0,2,4,6,8,10,12,14])             # Closed hat
        add(5, [6, 14], 80)                       # Open hat
        add(6, [3, 7, 11, 15], 60)               # Ride/perc
    
    elif style == "dnb":
        add(1, [0, 10])                           # Kick
        add(2, [4, 12, 14])                       # Snare with ghost
        add(4, [0,2,4,6,8,10,12,14])             # Fast hats
        add(3, [4])                               # Clap accent
    
    elif style == "hiphop":
        add(1, [0, 5, 8, 13])                    # Boom bap kick
        add(2, [4, 12])                           # Snare
        add(4, [0, 2, 4, 6, 8, 10, 12, 14])      # Hats
        add(5, [6, 14], 70)                       # Open hat
    
    return patterns


# ─── CLI Interface ───────────────────────────────────────────────────────────

class SeqtrakCLI:
    def __init__(self):
        self.project = Project()
        self.running = True
        self.selected_track = 1  # Currently selected track channel
        self.selected_pattern = 0
    
    def run(self):
        self.show_banner()
        while self.running:
            try:
                self.show_main_menu()
            except KeyboardInterrupt:
                console.print("\n[yellow]Use 'quit' to exit.[/yellow]")
            except Exception as e:
                console.print(f"[red]Error: {e}[/red]")
    
    def show_banner(self):
        banner = Text()
        banner.append("╔══════════════════════════════════════════╗\n", style="bright_cyan")
        banner.append("║   ", style="bright_cyan")
        banner.append("SeqTrak Composer", style="bold bright_white")
        banner.append("                   ║\n", style="bright_cyan")
        banner.append("║   ", style="bright_cyan")
        banner.append("MIDI Composition Tool for Yamaha Seqtrak", style="dim")
        banner.append("  ║\n", style="bright_cyan")
        banner.append("╚══════════════════════════════════════════╝", style="bright_cyan")
        console.print(banner)
        console.print(f"  Project: [bold]{self.project.name}[/bold]  "
                      f"BPM: [bold]{self.project.bpm}[/bold]  "
                      f"Scale: [bold]{self.project.scale_root} {self.project.scale_name}[/bold]\n")
    
    def show_main_menu(self):
        console.print()
        table = Table(title="Main Menu", box=box.ROUNDED, title_style="bold bright_cyan",
                      show_header=False, padding=(0, 2))
        table.add_column("Key", style="bold bright_yellow", width=8)
        table.add_column("Action", style="white")
        
        table.add_row("[T]", "Track Overview & Selection")
        table.add_row("[E]", "Edit Pattern (Step Sequencer)")
        table.add_row("[N]", "Enter Notes (Scale-aware)")
        table.add_row("[D]", "Drum Pattern Generator")
        table.add_row("[R]", "Euclidean Rhythm Generator")
        table.add_row("[I]", "Import MIDI File")
        table.add_row("[X]", "Export MIDI File")
        table.add_row("[P]", "Project Settings (BPM, Scale, Name)")
        table.add_row("[S]", "Scene Editor")
        table.add_row("[V]", "Visualize Current Pattern")
        table.add_row("[W]", "Save Project")
        table.add_row("[L]", "Load Project")
        table.add_row("[Q]", "Quit")
        console.print(table)
        
        choice = Prompt.ask("Select", choices=["t","e","n","d","r","i","x","p","s","v","w","l","q"],
                           default="t").lower()
        
        actions = {
            "t": self.track_overview,
            "e": self.edit_pattern,
            "n": self.note_entry,
            "d": self.drum_generator,
            "r": self.euclidean_generator,
            "i": self.import_midi_menu,
            "x": self.export_midi_menu,
            "p": self.project_settings,
            "s": self.scene_editor,
            "v": self.visualize_pattern,
            "w": self.save_project,
            "l": self.load_project,
            "q": self.quit,
        }
        actions[choice]()
    
    # ─── Track Overview ──────────────────────────────────────────────────
    
    def track_overview(self):
        table = Table(title="Seqtrak Tracks", box=box.DOUBLE_EDGE, 
                      title_style="bold bright_cyan")
        table.add_column("Ch", style="bold", width=4)
        table.add_column("Track", width=10)
        table.add_column("Type", width=8)
        table.add_column("Patterns", width=10)
        table.add_column("Active", width=8)
        table.add_column("Notes", width=8)
        table.add_column("Bars", width=6)
        table.add_column("Muted", width=6)
        table.add_column("Vol", width=5)
        
        for ch in range(1, 12):
            track = self.project.get_track(ch)
            info = SEQTRAK_TRACKS[ch]
            active_pat = track.get_active_pattern()
            note_count = len(active_pat.notes)
            
            marker = "▸ " if ch == self.selected_track else "  "
            
            table.add_row(
                f"{marker}{ch}",
                f"[{info['color']}]{info['name']}[/{info['color']}]",
                info["type"],
                str(len(track.patterns)),
                f"P{track.active_pattern + 1}",
                str(note_count),
                str(active_pat.bars),
                "[red]M[/red]" if track.muted else "[green]—[/green]",
                str(track.volume),
            )
        
        console.print(table)
        
        ch = IntPrompt.ask("Select track (1-11) or 0 to go back", default=0)
        if 1 <= ch <= 11:
            self.selected_track = ch
            self.track_detail_menu()
    
    def track_detail_menu(self):
        track = self.project.get_track(self.selected_track)
        info = SEQTRAK_TRACKS[self.selected_track]
        
        console.print(f"\n[bold {info['color']}]── {info['name']} (Ch {self.selected_track}, {info['type']}) ──[/bold {info['color']}]")
        console.print(f"  Patterns: {len(track.patterns)}  Active: P{track.active_pattern + 1}  "
                      f"Muted: {'Yes' if track.muted else 'No'}  Volume: {track.volume}  Pan: {track.pan}")
        
        for i, pat in enumerate(track.patterns):
            marker = "▸" if i == track.active_pattern else " "
            console.print(f"  {marker} P{i+1}: {pat.name} — {len(pat.notes)} notes, {pat.bars} bars")
        
        console.print("\n  [a]ctivate pattern  [m]ute/unmute  [v]olume  [+]add pattern  [c]opy pattern  [b]ack")
        choice = Prompt.ask("Action", default="b").lower()
        
        if choice == "a":
            idx = IntPrompt.ask(f"Pattern number (1-{len(track.patterns)})", default=1) - 1
            if 0 <= idx < len(track.patterns):
                track.active_pattern = idx
                console.print(f"[green]Activated Pattern {idx + 1}[/green]")
        elif choice == "m":
            track.muted = not track.muted
            console.print(f"[yellow]Track {'muted' if track.muted else 'unmuted'}[/yellow]")
        elif choice == "v":
            vol = IntPrompt.ask("Volume (0-127)", default=track.volume)
            track.volume = max(0, min(127, vol))
        elif choice == "+":
            if len(track.patterns) < MAX_PATTERNS_PER_TRACK:
                name = Prompt.ask("Pattern name", default=f"Pattern {len(track.patterns)+1}")
                track.add_pattern(name)
                console.print(f"[green]Added pattern: {name}[/green]")
            else:
                console.print(f"[red]Maximum {MAX_PATTERNS_PER_TRACK} patterns reached[/red]")
        elif choice == "c":
            src = IntPrompt.ask(f"Copy from pattern (1-{len(track.patterns)})") - 1
            if 0 <= src < len(track.patterns) and len(track.patterns) < MAX_PATTERNS_PER_TRACK:
                new_pat = copy.deepcopy(track.patterns[src])
                new_pat.name = f"{new_pat.name} (copy)"
                track.patterns.append(new_pat)
                console.print(f"[green]Pattern copied[/green]")
    
    # ─── Step Sequencer (Pattern Edit) ───────────────────────────────────
    
    def edit_pattern(self):
        track = self.project.get_track(self.selected_track)
        pattern = track.get_active_pattern()
        info = SEQTRAK_TRACKS[self.selected_track]
        
        console.print(f"\n[bold {info['color']}]Step Editor: {info['name']} — {pattern.name}[/bold {info['color']}]")
        console.print(f"  Bars: {pattern.bars}  Steps: {pattern.total_steps}  Notes: {len(pattern.notes)}")
        
        self._show_pattern_grid(track, pattern)
        
        console.print("\n  Commands:")
        console.print("    [bold]a <step> [pitch] [vel] [dur][/bold] — Add note (e.g., 'a 0 C4 100 2')")
        console.print("    [bold]r <step> [pitch][/bold]            — Remove note at step")
        console.print("    [bold]bars <n>[/bold]                    — Set bar count (1-8)")
        console.print("    [bold]clear[/bold]                       — Clear all notes")
        console.print("    [bold]grid[/bold]                        — Show pattern grid")
        console.print("    [bold]b[/bold]                           — Back to main menu")
        
        while True:
            try:
                cmd = Prompt.ask(f"[{info['color']}]{info['name']}[/{info['color']}]").strip()
            except (KeyboardInterrupt, EOFError):
                break
            
            if not cmd:
                continue
            
            parts = cmd.split()
            action = parts[0].lower()
            
            if action == "b":
                break
            elif action == "grid":
                self._show_pattern_grid(track, pattern)
            elif action == "clear":
                if Confirm.ask("Clear all notes?"):
                    pattern.clear()
                    console.print("[yellow]Pattern cleared[/yellow]")
            elif action == "bars":
                if len(parts) > 1:
                    try:
                        n = int(parts[1])
                        if 1 <= n <= MAX_BARS:
                            pattern.bars = n
                            console.print(f"[green]Pattern set to {n} bars ({n * STEPS_PER_BAR} steps)[/green]")
                        else:
                            console.print(f"[red]Bars must be 1-{MAX_BARS}[/red]")
                    except ValueError:
                        console.print("[red]Invalid number[/red]")
            elif action == "a":
                self._add_note_from_cmd(pattern, parts[1:], track.track_type)
            elif action == "r":
                if len(parts) > 1:
                    try:
                        step = int(parts[1])
                        pitch = note_name_to_midi(parts[2]) if len(parts) > 2 else None
                        pattern.remove_note_at(step, pitch)
                        console.print(f"[yellow]Removed note at step {step}[/yellow]")
                    except (ValueError, IndexError) as e:
                        console.print(f"[red]Error: {e}[/red]")
            else:
                console.print("[dim]Unknown command. Type 'b' to go back.[/dim]")
    
    def _add_note_from_cmd(self, pattern, args, track_type):
        """Parse 'add' command args: step [pitch] [velocity] [duration]"""
        if not args:
            console.print("[red]Usage: a <step> [pitch] [velocity] [duration][/red]")
            return
        
        try:
            step = int(args[0])
        except ValueError:
            console.print("[red]Step must be a number[/red]")
            return
        
        # Default pitch: C3 for drums, use scale for synth
        if track_type == "drum":
            pitch = 60  # C3 — standard trigger note for drums
        else:
            pitch = 60  # Default C3
        
        if len(args) > 1:
            try:
                pitch = int(args[1])  # Allow raw MIDI number
            except ValueError:
                try:
                    pitch = note_name_to_midi(args[1])
                except ValueError as e:
                    console.print(f"[red]{e}[/red]")
                    return
        
        velocity = int(args[2]) if len(args) > 2 else 100
        duration = int(args[3]) if len(args) > 3 else 1
        
        try:
            pattern.add_note(pitch=pitch, step=step, velocity=velocity, duration=duration)
            console.print(f"[green]Added: step={step} note={midi_to_note_name(pitch)} vel={velocity} dur={duration}[/green]")
        except ValueError as e:
            console.print(f"[red]{e}[/red]")
    
    def _show_pattern_grid(self, track, pattern):
        """Display a visual step grid for the pattern."""
        grid = pattern.get_step_grid()
        total = pattern.total_steps
        info = SEQTRAK_TRACKS[track.channel]
        
        if track.track_type == "drum":
            # Simple on/off grid for drums
            for bar in range(pattern.bars):
                bar_start = bar * STEPS_PER_BAR
                header = f"  Bar {bar + 1}:  "
                steps_str = ""
                for s in range(STEPS_PER_BAR):
                    step = bar_start + s
                    if step in grid:
                        vel = grid[step][0].velocity
                        if vel > 100:
                            steps_str += f"[bold {info['color']}]█[/bold {info['color']}]"
                        elif vel > 50:
                            steps_str += f"[{info['color']}]▓[/{info['color']}]"
                        else:
                            steps_str += f"[dim {info['color']}]░[/dim {info['color']}]"
                    else:
                        steps_str += "[dim]·[/dim]"
                    
                    if s % 4 == 3 and s < 15:
                        steps_str += " "
                
                console.print(f"{header}{steps_str}")
            
            # Step numbers
            console.print("            1234 5678 9012 3456")
        
        else:
            # Piano roll style for synth tracks
            if not pattern.notes:
                console.print("  [dim](empty pattern)[/dim]")
                return
            
            # Find pitch range
            pitches = sorted(set(n.pitch for n in pattern.notes))
            if not pitches:
                return
            
            # Show each pitch row
            for pitch in reversed(pitches):
                name = midi_to_note_name(pitch).rjust(4)
                row = f"  {name} │"
                for bar in range(pattern.bars):
                    bar_start = bar * STEPS_PER_BAR
                    for s in range(STEPS_PER_BAR):
                        step = bar_start + s
                        notes_at = grid.get(step, [])
                        has_note = any(n.pitch == pitch for n in notes_at)
                        if has_note:
                            row += f"[{info['color']}]█[/{info['color']}]"
                        else:
                            row += "[dim]·[/dim]"
                        if s % 4 == 3 and s < 15:
                            row += " "
                    if bar < pattern.bars - 1:
                        row += "│"
                
                console.print(row)
    
    # ─── Scale-Aware Note Entry ──────────────────────────────────────────
    
    def note_entry(self):
        track = self.project.get_track(self.selected_track)
        info = SEQTRAK_TRACKS[self.selected_track]
        pattern = track.get_active_pattern()
        
        if info["type"] == "drum":
            console.print("[yellow]Note entry is for synth/sampler tracks. Use step editor or drum generator for drum tracks.[/yellow]")
            return
        
        console.print(f"\n[bold {info['color']}]Note Entry: {info['name']} — {pattern.name}[/bold {info['color']}]")
        console.print(f"  Scale: {self.project.scale_root} {self.project.scale_name}")
        
        # Show available scale degrees
        scale_notes = get_scale_notes(self.project.scale_root, self.project.scale_name, 2, 6)
        degrees_display = ", ".join(midi_to_note_name(n) for n in scale_notes[:14])
        console.print(f"  Available notes: {degrees_display}...")
        
        console.print("\n  Enter notes as: <step> <note> [velocity] [duration]")
        console.print("  Examples: '0 C4', '4 E4 80 2', '8 G4 100 4'")
        console.print("  Or enter a sequence: 'seq C4 E4 G4 C5' (auto-places on consecutive steps)")
        console.print("  Type 'b' to go back\n")
        
        current_step = 0
        
        while True:
            try:
                cmd = Prompt.ask(f"[{info['color']}]Step {current_step}>[/{info['color']}]").strip()
            except (KeyboardInterrupt, EOFError):
                break
            
            if cmd.lower() == "b":
                break
            
            parts = cmd.split()
            if not parts:
                continue
            
            # Sequence mode
            if parts[0].lower() == "seq":
                start_step = current_step
                vel = 100
                dur = 1
                for note_str in parts[1:]:
                    try:
                        pitch = note_name_to_midi(note_str)
                        pattern.add_note(pitch=pitch, step=start_step, velocity=vel, duration=dur)
                        console.print(f"  [green]+ Step {start_step}: {note_str}[/green]")
                        start_step += dur
                    except ValueError as e:
                        console.print(f"  [red]Skipping '{note_str}': {e}[/red]")
                current_step = start_step
                continue
            
            # Single note mode
            try:
                step = int(parts[0])
                if len(parts) < 2:
                    console.print("[red]Need at least: <step> <note>[/red]")
                    continue
                
                pitch = note_name_to_midi(parts[1])
                vel = int(parts[2]) if len(parts) > 2 else 100
                dur = int(parts[3]) if len(parts) > 3 else 1
                
                pattern.add_note(pitch=pitch, step=step, velocity=vel, duration=dur)
                console.print(f"  [green]+ Step {step}: {midi_to_note_name(pitch)} vel={vel} dur={dur}[/green]")
                current_step = step + dur
            except (ValueError, IndexError) as e:
                console.print(f"  [red]Error: {e}[/red]")
    
    # ─── Drum Pattern Generator ──────────────────────────────────────────
    
    def drum_generator(self):
        console.print("\n[bold bright_cyan]Drum Pattern Generator[/bold bright_cyan]")
        console.print("  Available styles:")
        styles = ["basic_4x4", "breakbeat", "trap", "house", "techno", "dnb", "hiphop"]
        for i, s in enumerate(styles, 1):
            console.print(f"    {i}. {s}")
        
        choice = Prompt.ask("Style", choices=[str(i) for i in range(1, len(styles)+1)])
        style = styles[int(choice) - 1]
        
        bars = IntPrompt.ask("Bars (1-8)", default=1)
        bars = max(1, min(MAX_BARS, bars))
        
        overwrite = Confirm.ask("Overwrite existing patterns?", default=False)
        
        drum_data = generate_drum_pattern(style, bars)
        
        for ch, hits in drum_data.items():
            if not hits:
                continue
            track = self.project.get_track(ch)
            pattern = track.get_active_pattern()
            
            if overwrite:
                pattern.clear()
            
            pattern.bars = bars
            for step, vel in hits:
                pattern.add_note(pitch=60, step=step, velocity=vel)
        
        total_notes = sum(len(hits) for hits in drum_data.values())
        console.print(f"[green]Generated '{style}' pattern: {total_notes} hits across drum tracks[/green]")
    
    # ─── Euclidean Rhythm Generator ──────────────────────────────────────
    
    def euclidean_generator(self):
        console.print("\n[bold bright_cyan]Euclidean Rhythm Generator[/bold bright_cyan]")
        
        ch = IntPrompt.ask(f"Track channel (current: {self.selected_track})", default=self.selected_track)
        if ch < 1 or ch > 11:
            console.print("[red]Invalid channel[/red]")
            return
        
        steps = IntPrompt.ask("Total steps", default=16)
        pulses = IntPrompt.ask("Pulses (hits)", default=5)
        rotation = IntPrompt.ask("Rotation offset", default=0)
        
        hit_steps = generate_euclidean_rhythm(steps, pulses, rotation)
        
        # Preview
        preview = ""
        for s in range(steps):
            if s in hit_steps:
                preview += "[bold bright_yellow]█[/bold bright_yellow]"
            else:
                preview += "[dim]·[/dim]"
            if s % 4 == 3 and s < steps - 1:
                preview += " "
        
        console.print(f"  Pattern: {preview}")
        console.print(f"  Hits: {len(hit_steps)} / {steps}")
        
        if Confirm.ask("Apply to track?"):
            track = self.project.get_track(ch)
            pattern = track.get_active_pattern()
            bars_needed = max(1, (steps + STEPS_PER_BAR - 1) // STEPS_PER_BAR)
            pattern.bars = min(bars_needed, MAX_BARS)
            
            info = SEQTRAK_TRACKS[ch]
            pitch = 60 if info["type"] == "drum" else note_name_to_midi(f"{self.project.scale_root}3")
            
            for step in hit_steps:
                if step < pattern.total_steps:
                    pattern.add_note(pitch=pitch, step=step, velocity=100)
            
            console.print(f"[green]Applied Euclidean rhythm to {info['name']}[/green]")
    
    # ─── MIDI Import ─────────────────────────────────────────────────────
    
    def import_midi_menu(self):
        console.print("\n[bold bright_cyan]Import MIDI File[/bold bright_cyan]")
        path = Prompt.ask("MIDI file path").strip().strip("'\"")
        
        if not os.path.exists(path):
            console.print(f"[red]File not found: {path}[/red]")
            return
        
        # Analyze first
        try:
            info = analyze_midi(path)
        except Exception as e:
            console.print(f"[red]Error reading MIDI: {e}[/red]")
            return
        
        table = Table(title=f"MIDI Analysis: {info['filename']}", box=box.ROUNDED)
        table.add_column("Source Ch", width=10)
        table.add_column("Track Name", width=20)
        table.add_column("Notes", width=8)
        table.add_column("Range", width=15)
        table.add_column("→ Seqtrak", width=15)
        
        for ch, ch_info in sorted(info["channels"].items()):
            lo = midi_to_note_name(ch_info["note_range"][0]) if ch_info["note_range"][1] > 0 else "—"
            hi = midi_to_note_name(ch_info["note_range"][1]) if ch_info["note_range"][1] > 0 else "—"
            target = SEQTRAK_TRACKS[ch]["name"] if ch <= 11 else "[dim]unmapped[/dim]"
            
            table.add_row(
                str(ch),
                ch_info.get("track_name") or "—",
                str(ch_info["note_count"]),
                f"{lo} — {hi}",
                target,
            )
        
        console.print(table)
        console.print(f"  Tempo: {info['tempo']} BPM  Duration: {info['duration_seconds']:.1f}s  "
                      f"Type: {info['type']}  Tracks: {info['num_tracks']}")
        
        # Channel mapping
        use_custom = Confirm.ask("Custom channel mapping? (No = direct 1:1)", default=False)
        channel_map = None
        
        if use_custom:
            channel_map = {}
            for src_ch in sorted(info["channels"].keys()):
                ch_info = info["channels"][src_ch]
                tgt = IntPrompt.ask(
                    f"  Map Ch {src_ch} ({ch_info.get('track_name', '?')}, {ch_info['note_count']} notes) → Seqtrak Ch (0=skip)",
                    default=min(src_ch, 11)
                )
                if 1 <= tgt <= 11:
                    channel_map[src_ch] = tgt
        
        # Quantize setting
        quant = Prompt.ask("Quantize", choices=list(QUANTIZE_OPTIONS.keys()), default=self.project.quantize)
        
        max_bars = IntPrompt.ask(f"Max bars per pattern (1-{MAX_BARS})", default=MAX_BARS)
        
        if Confirm.ask("Proceed with import?"):
            import_midi(path, self.project, channel_map, quant, min(max_bars, MAX_BARS))
    
    # ─── MIDI Export ─────────────────────────────────────────────────────
    
    def export_midi_menu(self):
        console.print("\n[bold bright_cyan]Export MIDI File[/bold bright_cyan]")
        
        # Show what will be exported
        table = Table(title="Export Preview", box=box.SIMPLE)
        table.add_column("Track", width=12)
        table.add_column("Ch", width=4)
        table.add_column("Pattern", width=15)
        table.add_column("Notes", width=8)
        table.add_column("Bars", width=6)
        
        for ch in range(1, 12):
            track = self.project.get_track(ch)
            pat = track.get_active_pattern()
            info = SEQTRAK_TRACKS[ch]
            
            if pat.notes:
                table.add_row(
                    f"[{info['color']}]{info['name']}[/{info['color']}]",
                    str(ch),
                    pat.name,
                    str(len(pat.notes)),
                    str(pat.bars),
                )
        
        console.print(table)
        
        default_name = self.project.name.replace(" ", "_").lower()
        path = Prompt.ask("Output file path", default=f"{default_name}.mid")
        
        if not path.endswith(".mid") and not path.endswith(".midi"):
            path += ".mid"
        
        export_all = Confirm.ask("Export all patterns (concatenated)? No = active only", default=False)
        
        export_midi(self.project, path, export_all)
    
    # ─── Project Settings ────────────────────────────────────────────────
    
    def project_settings(self):
        console.print("\n[bold bright_cyan]Project Settings[/bold bright_cyan]")
        console.print(f"  Name: {self.project.name}")
        console.print(f"  BPM:  {self.project.bpm}")
        console.print(f"  Scale: {self.project.scale_root} {self.project.scale_name}")
        console.print(f"  Quantize: {self.project.quantize}")
        
        console.print("\n  [n]ame  [b]pm  [s]cale  [q]uantize  [back]")
        choice = Prompt.ask("Setting", default="back").lower()
        
        if choice == "n":
            self.project.name = Prompt.ask("Project name", default=self.project.name)
        elif choice == "b":
            bpm = IntPrompt.ask(f"BPM ({BPM_MIN}-{BPM_MAX})", default=self.project.bpm)
            self.project.bpm = max(BPM_MIN, min(BPM_MAX, bpm))
        elif choice == "s":
            root = Prompt.ask("Root note", default=self.project.scale_root)
            if root.upper().replace("B","#") in NOTE_NAMES or root.upper() in NOTE_NAMES:
                self.project.scale_root = root.upper()
            else:
                console.print(f"[red]Invalid root note. Use: {', '.join(NOTE_NAMES)}[/red]")
                return
            
            console.print(f"  Scales: {', '.join(SCALES.keys())}")
            scale = Prompt.ask("Scale", default=self.project.scale_name)
            if scale in SCALES:
                self.project.scale_name = scale
            else:
                console.print(f"[red]Unknown scale[/red]")
        elif choice == "q":
            q = Prompt.ask("Quantize", choices=list(QUANTIZE_OPTIONS.keys()), 
                          default=self.project.quantize)
            self.project.quantize = q
    
    # ─── Scene Editor ────────────────────────────────────────────────────
    
    def scene_editor(self):
        console.print("\n[bold bright_cyan]Scene Editor[/bold bright_cyan]")
        console.print(f"  Scenes: {len(self.project.scenes)} / {MAX_SCENES}")
        
        if self.project.scenes:
            table = Table(box=box.SIMPLE)
            table.add_column("#", width=4)
            table.add_column("Name", width=15)
            table.add_column("Repeats", width=8)
            table.add_column("Pattern Config", width=40)
            
            for i, scene in enumerate(self.project.scenes):
                config = ", ".join(
                    f"{SEQTRAK_TRACKS[int(ch)]['name']}:P{pidx+1}"
                    for ch, pidx in scene.pattern_indices.items()
                ) or "default"
                table.add_row(str(i+1), scene.name, str(scene.repeats), config)
            
            console.print(table)
        
        console.print("\n  [a]dd scene  [e]dit scene  [d]elete scene  [b]ack")
        choice = Prompt.ask("Action", default="b").lower()
        
        if choice == "a":
            if len(self.project.scenes) >= MAX_SCENES:
                console.print(f"[red]Maximum {MAX_SCENES} scenes[/red]")
                return
            
            name = Prompt.ask("Scene name", default=f"Scene {len(self.project.scenes) + 1}")
            scene = Scene(name=name)
            
            # Set pattern indices for each track
            console.print("  Set pattern index for each track (Enter to skip/use current):")
            for ch in range(1, 12):
                track = self.project.get_track(ch)
                info = SEQTRAK_TRACKS[ch]
                if len(track.patterns) > 1:
                    idx = IntPrompt.ask(
                        f"    {info['name']} (1-{len(track.patterns)})",
                        default=track.active_pattern + 1
                    ) - 1
                    scene.pattern_indices[str(ch)] = max(0, min(idx, len(track.patterns) - 1))
            
            scene.repeats = IntPrompt.ask("Repeats", default=1)
            self.project.scenes.append(scene)
            console.print(f"[green]Added scene: {name}[/green]")
        
        elif choice == "d":
            if self.project.scenes:
                idx = IntPrompt.ask(f"Delete scene (1-{len(self.project.scenes)})") - 1
                if 0 <= idx < len(self.project.scenes):
                    removed = self.project.scenes.pop(idx)
                    console.print(f"[yellow]Deleted scene: {removed.name}[/yellow]")
    
    # ─── Pattern Visualization ───────────────────────────────────────────
    
    def visualize_pattern(self):
        track = self.project.get_track(self.selected_track)
        pattern = track.get_active_pattern()
        info = SEQTRAK_TRACKS[self.selected_track]
        
        console.print(f"\n[bold {info['color']}]Pattern: {info['name']} — {pattern.name}[/bold {info['color']}]")
        console.print(f"  Bars: {pattern.bars}  Steps: {pattern.total_steps}  Notes: {len(pattern.notes)}  Swing: {pattern.swing}")
        
        if not pattern.notes:
            console.print("  [dim](empty)[/dim]")
            return
        
        self._show_pattern_grid(track, pattern)
        
        # Note list
        console.print(f"\n  [bold]Note List:[/bold]")
        sorted_notes = sorted(pattern.notes, key=lambda n: (n.step, n.pitch))
        for note in sorted_notes[:50]:  # Limit display
            console.print(f"    Step {note.step:3d}: {midi_to_note_name(note.pitch):>4s}  "
                         f"vel={note.velocity:3d}  dur={note.duration}  prob={note.probability}%")
        
        if len(pattern.notes) > 50:
            console.print(f"    ... and {len(pattern.notes) - 50} more notes")
    
    # ─── Save/Load ───────────────────────────────────────────────────────
    
    def save_project(self):
        default = self.project.name.replace(" ", "_").lower() + ".json"
        path = Prompt.ask("Save path", default=default)
        if not path.endswith(".json"):
            path += ".json"
        self.project.save(path)
    
    def load_project(self):
        path = Prompt.ask("Load path").strip().strip("'\"")
        if not os.path.exists(path):
            console.print(f"[red]File not found: {path}[/red]")
            return
        try:
            self.project = Project.load(path)
            self.selected_track = 1
            self.selected_pattern = 0
        except Exception as e:
            console.print(f"[red]Error loading project: {e}[/red]")
    
    def quit(self):
        if Confirm.ask("Save before quitting?", default=True):
            self.save_project()
        self.running = False
        console.print("[bright_cyan]Goodbye![/bright_cyan]")


# ─── Non-Interactive CLI ─────────────────────────────────────────────────────

def cli_import(args):
    """Non-interactive import command."""
    project = Project()
    if args.project and os.path.exists(args.project):
        project = Project.load(args.project)
    
    channel_map = None
    if args.channel_map:
        channel_map = {}
        for mapping in args.channel_map.split(","):
            src, tgt = mapping.split(":")
            channel_map[int(src)] = int(tgt)
    
    import_midi(args.input, project, channel_map, args.quantize, args.max_bars)
    
    if args.output:
        export_midi(project, args.output)
    
    if args.save:
        project.save(args.save)


def cli_export(args):
    """Non-interactive export command."""
    if not os.path.exists(args.project):
        console.print(f"[red]Project file not found: {args.project}[/red]")
        return
    
    project = Project.load(args.project)
    export_midi(project, args.output, args.all_patterns)


def cli_analyze(args):
    """Analyze a MIDI file."""
    info = analyze_midi(args.input)
    
    table = Table(title=f"MIDI Analysis: {info['filename']}", box=box.ROUNDED)
    table.add_column("Channel", width=10)
    table.add_column("Track Name", width=20)
    table.add_column("Notes", width=8)
    table.add_column("Range", width=15)
    table.add_column("Unique Notes", width=12)
    
    for ch, ch_info in sorted(info["channels"].items()):
        lo = midi_to_note_name(ch_info["note_range"][0]) if ch_info["note_range"][1] > 0 else "—"
        hi = midi_to_note_name(ch_info["note_range"][1]) if ch_info["note_range"][1] > 0 else "—"
        
        table.add_row(
            str(ch),
            ch_info.get("track_name") or "—",
            str(ch_info["note_count"]),
            f"{lo} — {hi}",
            str(len(ch_info["notes"])),
        )
    
    console.print(table)
    console.print(f"\n  Tempo: {info['tempo']} BPM")
    console.print(f"  Duration: {info['duration_seconds']:.1f}s")
    console.print(f"  MIDI Type: {info['type']}")
    console.print(f"  Tracks: {info['num_tracks']}")
    console.print(f"  Ticks/Beat: {info['ticks_per_beat']}")


def cli_generate(args):
    """Generate a drum pattern and export."""
    project = Project(name=args.name or f"Generated {args.style}", bpm=args.bpm)
    
    drum_data = generate_drum_pattern(args.style, args.bars)
    for ch, hits in drum_data.items():
        track = project.get_track(ch)
        pattern = track.get_active_pattern()
        pattern.bars = args.bars
        for step, vel in hits:
            pattern.add_note(pitch=60, step=step, velocity=vel)
    
    export_midi(project, args.output)
    
    if args.save:
        project.save(args.save)


# ─── Main ────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="SeqTrak Composer — MIDI composition tool for Yamaha Seqtrak",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s                                    # Interactive mode
  %(prog)s analyze input.mid                  # Analyze a MIDI file
  %(prog)s import input.mid -o output.mid     # Import and re-export for Seqtrak
  %(prog)s import input.mid -m "1:1,2:2,10:3" # Import with channel remapping
  %(prog)s export project.json -o output.mid  # Export project to MIDI
  %(prog)s generate techno -o beat.mid        # Generate a drum pattern
  %(prog)s generate house --bars 4 -o house.mid

Seqtrak Channel Map:
  Ch 1: Kick    Ch 4: Hat 1   Ch 7: Perc 2    Ch 10: DX (FM)
  Ch 2: Snare   Ch 5: Hat 2   Ch 8: Synth 1   Ch 11: Sampler
  Ch 3: Clap    Ch 6: Perc 1  Ch 9: Synth 2
        """
    )
    
    subparsers = parser.add_subparsers(dest="command")
    
    # Interactive mode (default)
    
    # Analyze command
    p_analyze = subparsers.add_parser("analyze", help="Analyze a MIDI file")
    p_analyze.add_argument("input", help="MIDI file to analyze")
    
    # Import command
    p_import = subparsers.add_parser("import", help="Import MIDI file")
    p_import.add_argument("input", help="MIDI file to import")
    p_import.add_argument("-o", "--output", help="Output MIDI file path")
    p_import.add_argument("-p", "--project", help="Existing project file to import into")
    p_import.add_argument("-s", "--save", help="Save project to JSON after import")
    p_import.add_argument("-m", "--channel-map", help="Channel mapping (e.g., '1:1,2:2,10:3')")
    p_import.add_argument("-q", "--quantize", default="1/16", 
                         choices=list(QUANTIZE_OPTIONS.keys()), help="Quantize resolution")
    p_import.add_argument("--max-bars", type=int, default=8, help="Max bars per pattern")
    
    # Export command
    p_export = subparsers.add_parser("export", help="Export project to MIDI")
    p_export.add_argument("project", help="Project JSON file")
    p_export.add_argument("-o", "--output", default="output.mid", help="Output MIDI file")
    p_export.add_argument("--all-patterns", action="store_true", help="Export all patterns")
    
    # Generate command
    p_gen = subparsers.add_parser("generate", help="Generate drum pattern")
    p_gen.add_argument("style", choices=["basic_4x4","breakbeat","trap","house","techno","dnb","hiphop"],
                      help="Drum pattern style")
    p_gen.add_argument("-o", "--output", default="generated.mid", help="Output MIDI file")
    p_gen.add_argument("--bpm", type=int, default=120, help="Tempo BPM")
    p_gen.add_argument("--bars", type=int, default=1, help="Number of bars")
    p_gen.add_argument("-n", "--name", help="Project name")
    p_gen.add_argument("-s", "--save", help="Save project JSON")
    
    args = parser.parse_args()
    
    if args.command is None:
        # Interactive mode
        cli = SeqtrakCLI()
        cli.run()
    elif args.command == "analyze":
        cli_analyze(args)
    elif args.command == "import":
        cli_import(args)
    elif args.command == "export":
        cli_export(args)
    elif args.command == "generate":
        cli_generate(args)


if __name__ == "__main__":
    main()
